# ----
# Site

title: Doc Portal
description: BOIPA API documentation.
url: https://ipgcarts.com/docportal/
google_analytics_key:

collections:
  documentation:
    title: Documentation
    position: 1
    
  api:
    title: Direct API
    position: 2 
  hpp:
    title: Hosted Payments
    position: 3   

  testing:
    title: Testing
    position: 4
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: default

# -----
# Build


# -----------
# CloudCannon

version: 3.0.3
